# Generated by Django 5.1.3 on 2024-11-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivospruebas',
            fields=[
                ('idarchivospruebas', models.IntegerField(db_column='idArchivosPruebas', primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(choices=[('pdf', 'pdf'), ('excel', 'excel')], max_length=5)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField()),
            ],
            options={
                'db_table': 'archivospruebas',
            },
        ),
        migrations.CreateModel(
            name='Interruptores',
            fields=[
                ('idinterruptores', models.IntegerField(db_column='idInterruptores', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'interruptores',
            },
        ),
        migrations.CreateModel(
            name='MedicionesTransformadores',
            fields=[
                ('idmediciones_transformadores', models.IntegerField(db_column='idMediciones_Transformadores', primary_key=True, serialize=False)),
                ('relacion_transformacion', models.DecimalField(decimal_places=3, max_digits=4)),
                ('resistencia_devanados', models.DecimalField(decimal_places=3, max_digits=4)),
                ('corriente_excitacion', models.DecimalField(decimal_places=3, max_digits=4)),
                ('factor_potencia', models.DecimalField(decimal_places=3, max_digits=4)),
                ('calidad_aceite', models.DecimalField(decimal_places=3, max_digits=4)),
                ('inhibidor_oxidacion', models.DecimalField(decimal_places=3, max_digits=4)),
                ('compuestos_furanicos', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'mediciones_transformadores',
            },
        ),
        migrations.CreateModel(
            name='Transformadores',
            fields=[
                ('idtransformadores', models.IntegerField(db_column='idTransformadores', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'transformadores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Técnico', 'Técnico'), ('Administrador', 'Administrador')], max_length=13)),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Medicionesinterruptores',
            fields=[
                ('idmediciones_interruptores', models.IntegerField(db_column='idMediciones_Interruptores', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('corriente_nominal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tension_operacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_operacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interruptores_idinterruptores', models.ForeignKey(blank=True, db_column='Interruptores_idInterruptores', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.interruptores')),
            ],
            options={
                'db_table': 'medicionesinterruptores',
            },
        ),
        migrations.CreateModel(
            name='Analisisgasesdisueltos',
            fields=[
                ('idanalisisgasesdisueltos', models.IntegerField(db_column='idAnalisisGasesDisueltos', primary_key=True, serialize=False)),
                ('hidrogeno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etileno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acetileno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dioxido_carbono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monoxido_carbono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mediciones_transformadores_idmediciones_transformadores', models.ForeignKey(blank=True, db_column='Mediciones_Transformadores_idMediciones_Transformadores', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicionestransformadores')),
            ],
            options={
                'db_table': 'analisisgasesdisueltos',
            },
        ),
        migrations.CreateModel(
            name='Analisisaceitefisicoquimico',
            fields=[
                ('idanalisisaceitefisicoquimico', models.IntegerField(db_column='idAnalisisAceiteFisicoQuimico', primary_key=True, serialize=False)),
                ('rigidez_dieletrica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tension_interfacial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_acidez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contenido_humedad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_potencia_liquido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mediciones_transformadores_idmediciones_transformadores', models.ForeignKey(blank=True, db_column='Mediciones_Transformadores_idMediciones_Transformadores', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicionestransformadores')),
            ],
            options={
                'db_table': 'analisisaceitefisicoquimico',
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idalerta', models.IntegerField(db_column='idAlerta', primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha_generacion', models.DateTimeField()),
                ('mediciones_interruptores', models.ForeignKey(blank=True, db_column='MedicionesInterruptores_idMediciones_Interruptores', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicionesinterruptores')),
                ('mediciones_transformadores', models.ForeignKey(blank=True, db_column='Mediciones_Transformadores_idMediciones_Transformadores', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicionestransformadores')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.AddField(
            model_name='medicionestransformadores',
            name='transformadores',
            field=models.ForeignKey(blank=True, db_column='Transformadores_idTransformadores', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.transformadores'),
        ),
    ]
